- hosts: servers
  remote_user: user
  become: yes
  tasks:
    - ansible.builtin.service:
        name: nginx
        state: started
      become: yes
      become_method: sudo
    - name: copy index.html
      ansible.builtin.copy:
        src: /home/user/LEARN/homeworks/Terraform/playbook-test/data/index.html
        dest: /var/www/html/index.html